---
- name: Register DNS Records on Windows DNS Server
  hosts: all
  gather_facts: false

  tasks:
    - name: Set variables for DNS registration
      ansible.builtin.set_fact:
        dns_zone: "jvh.local"
        dns_ttl: 3600

    - name: Set variables for VM Name and IP address
      ansible.builtin.set_fact:
        vm_name: "{{ vm_fqdn.split('.')[0] }}"
        vm_ip: "{{ vm_ip }}"
    
    - name: Create A Record for {{ vm_name }} in {{ dns_zone }}
      ansible.windows.win_dns_record:
        name: "{{ vm_name }}"
        type: A
        value: "{{ vm_ip }}"
        zone: "{{ dns_zone }}"
        state: present
        ttl: "{{ dns_ttl | default(3600) }}"
      register: dns_record_result