---
- name: Wait for Nutanix VM Information
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for VM information to be available from Nutanix Prism
      nutanix.ncp.ntnx_vms_info_v2:
        ext_id: "{{ deployed_vm_extId }}"
        validate_certs: false
      register: vm_info
      until: >
        "jvh.local" in (vm_info.response | default({}) | json_query('guest_tools.guest_info.dns_name.value') | default(''))
      retries: 25
      delay: 15
      failed_when: false

    - name: Display VM FDQN and VM IP Address
      ansible.builtin.debug:
        msg: >
          VM FQDN: {{ vm_info.response.guest_tools.guest_info.dns_name.value }},
          VM IP: {{ vm_info.response.nics[0].nic_network_info.ipv4_info.learned_ip_addresses[0].value }}

    - name: Return VM IP address
      ansible.builtin.set_stats:
        data:
          vm_ip: "{{ vm_info.response.nics[0].nic_network_info.ipv4_info.learned_ip_addresses[0].value }}"
        per_host: false